image: alpine

stages:
  - Package
  - Compile
  - Output Files
  - Test

Block3.T08G06.tar.gz:
  stage: Package
  script:
    - tar -czvf Block3.T08G06.tar.gz CMakeLists.txt src/
  artifacts:
    paths:
      - Block3.T08G06.tar.gz

CMake Build:
  image: mickare/cmake-clang
  stage: Compile
  dependencies:
    - Block3.T08G06.tar.gz
  artifacts:
    paths:
      - build/
  script:
    - mkdir extract; cd extract
    - tar -xzvf ../Block3.T08G06.tar.gz
    - mkdir ../build; cd ../build
    - cmake ../extract && make

Correct Output Files:
  stage: Output Files
  dependencies:
    - CMake Build
  script:
    - cd build
    - ls peer

Peer Hash Full Cycle:
  stage: Test
  image: python:3.7-stretch
  dependencies:
    - CMake Build
  script:
    - python3.7 ./test/sr.py -f ./test/services/peer_client_full_cycle.service

Peer Hash Implementation:
  stage: Test
  image: python:3.7-stretch
  dependencies:
    - CMake Build
  script:
    - python3.7 ./test/sr.py -f ./test/services/peer_client_request_this_full.service

Peer Lookup Next:
  stage: Test
  image: python:3.7-stretch
  dependencies:
    - CMake Build
  script:
    - python3.7 ./test/sr.py -f ./test/services/peer_lookup_next.service

Peer Lookup Other:
  stage: Test
  image: python:3.7-stretch
  dependencies:
    - CMake Build
  script:
    - python3.7 ./test/sr.py -f ./test/services/peer_lookup_other.service